return {
  { "mini.indentscope", enabled = false },
  { "mini.pairs", enabled = false },

  { "catppuccin", enabled = false },
  -- { "tokyonight.nvim", enabled = false },
  { "nvim-treesitter-context", enabled = false },
  { "flash.nvim", enabled = false},
  { "nvim-notify", enabled = false },
  { "noice.nvim", enabled = false },
  { "dashboard-nvim", enabled = false },
  { "nvim-spectre", enabled = false },
  { "vim-illuminate", enabled = false},
  -- { "plenary.nvim", enabled = false},
  { "vim-startuptime", enabled = false},
  -- { "nui.nvim", enabled = false},
  { "mini.bufremove", enabled = false},
  { "conform.nvim", enabled = false},
  { "todo-comments.nvim", enabled = false},
  { "persistence.nvim", enabled = false},
  -- { "nvim-web-devicons", enabled = false},
  { "nvim-ts-autotag", enabled = false},
  { "neoconf.nvim", enabled = false},
  -- { "LuaSnip", enabled = false},
  -- { "indent-blankline.nvim", enabled = false},
  { "cmp_luasnip", enabled = false},
  { "cmp-path", enabled = false},
  { "cmp-buffer", enabled = false},

}
